version: "3.2"

services:
  server:
    image: nginx:latest
    container_name: server
    ports:
      - 8080:80
    volumes:
      - ./dockerfiles/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - api

  php:
    image: xdebug_php
    container_name: php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - api

  mysql:
    image: mariadb:10.6
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./dockerfiles/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: mohammad
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - api

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 30:80
    environment:
      PMA_HOST: mysql
    networks:
      - api


networks:
  api:
    driver: bridge